import java.util.Scanner;  //Guess A Number Game by Heather Ventresco

public class NumberGame {

	public static void main(String[] args) {

		Scanner input = new Scanner(System.in);
		int user, computer;
		int numofgames = 0; //number of games played
		int correctguesses=0;  //number of correct guesses
		int wrongguesses=0; //number of wrong guesses
		
		computer = 1 + (int) ( Math.random() * 10 );  //random number generated by computer
		//System.out.print("The computer chose ");
		//System.out.println(computer);  
		
		System.out.println("Guess A Number 1 to 10:");
		user = input.nextInt();
		numofgames++;  // number of games played
		
		if (user < 1 || user > 10) //verify number range
	    {      
	        System.out.println("Invalid Number"); 
	        System.exit(0);
	    }
		else {
		}
		   System.out.println("Correct Number Range"); 
	    if ( user == computer )  //user chose right number
	    {      
            System.out.println("You win!"); 
            correctguesses++;  //number of correct guesses

        } 
		else if ( user < computer )  //user guessed too low 
	    {      
            System.out.println("Your guess is too low"); 
            wrongguesses++; //wrong guess
           
        } 
		else  //user guessed too high
	    {      
            System.out.println("Your guess is too high"); 
            wrongguesses++; //wrong guess
        } 
	    
	    String Replay;
	    System.out.println("Would you like to play again? Y/N"); 
	    Replay =input.next();  //user enters y or n
	    
	     if (Replay.toUpperCase().equals("Y"))  //user enters yes
	            System.out.println("Restart."); 
	        else								//user enters no
	            System.out.println("Good Bye.");
	     do 
	     {
	    	 computer = 1 + (int) ( Math.random() * 10 );  //random number generated by computer
				//System.out.print("The computer chose ");
				//System.out.println(computer);  
				
			System.out.println("Guess A Number 1 to 10:");
			user = input.nextInt();
			numofgames++;  // number of games played
			
			
			if (user < 1 || user > 10) //verify number range
		    {      
		        System.out.println("Invalid Number"); 
		        System.exit(0);
		    }
			else {
			}
			   System.out.println("Correct Number Range"); 
		    if ( user == computer )  //user chose right number
		    {      
	            System.out.println("You win!");
	            correctguesses++;  //number of correct guesses

	        } 
			else if ( user < computer )  //user guessed too low 
		    {      
	            System.out.println("Your guess is too low"); 
	            wrongguesses++; //wrong guess
	        } 
			else  //user guessed too high
		    {      
	            System.out.println("Your guess is too high"); 
	            wrongguesses++; //wrong guess
	        } 
		    
		  
		    System.out.println("Would you like to play again? Y/N"); 
		    Replay =input.next();
		    
		     if (Replay.toUpperCase().equals("Y"))
		            System.out.println("Run program again.");
		        else
		            System.out.println("Good Bye.");
	    	 
	     } while (Replay.toUpperCase().equals("Y")); //keep restarting program as long as user says yes
	     
	     System.out.println("You played " + numofgames + " games."); //how many games user played
	     System.out.println("You had " + correctguesses + " correct guesses."); //number of games guessed right
	     System.out.println("You had " + wrongguesses + " wrong guesses."); //number of games guessed wrong
	     System.out.println("You had " + 100f * correctguesses / numofgames + "% correct guesses."); //percentage of correct guesses
	}
	}

